# Generated by Django 6.0.3 on 2026-07-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldbyark_app', '0006_destination_destination_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='package_type',
            field=models.CharField(choices=[('international', 'International'), ('domestic', 'Domestic (India)'), ('hot_selling', 'HOT SELLING')], default='domestic', help_text='Category of the tour package', max_length=20),
        ),
    ]
