# Generated by Django 6.0.3 on 2026-07-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldbyark_app', '0007_tourpackage_package_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourpackage',
            name='package_type',
            field=models.CharField(choices=[('international', 'International'), ('domestic', 'Domestic (India)'), ('hot_selling', 'Hot Selling')], default='domestic', help_text='Category of the tour package', max_length=20),
        ),
    ]
